# Working directory
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
include_ext = ["go"]

exclude_dir = []

include_dir = []

exclude_file = []

delay = 1500 

stop_on_error = true

log = "air_errors.log"

[log]
# Show log time
time = false

[color]
# Customize color 
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true